import './globals.sass'
import { Balsamiq_Sans } from 'next/font/google'

const balsamiq_Sans = Balsamiq_Sans({ weight: ["400" , "700"], subsets: ["cyrillic"] });

export const metadata = {
  title: 'App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body className={balsamiq_Sans.className}>{children}</body>
    </html>
  )
}
